msg = 'rebirth of a man'
print(msg)
print(len(msg))
print(msg[3])
print(msg[3:13])
print(msg[:13])
print(msg[1:15])
print(msg[1:15:2])
print(msg.count('O'))
print(msg.upper().count('O'))
print(msg.replace('man','cat'))
print('man' in msg)
print(msg.find('man'))
a = msg.split()
print(a[0])
print(a[3])