name = input('whats your full name ? ')
print(name.upper())
print(name.lower())
a = name.split()
b = ''.join(a)
print('this name lenght is : ', len(b))
### OR print(len(n) - n.count(' '))
print('the first name has',len(a[0]),' characters ')
### OR print(n.find(' '))  
