from calculator import SpurGear

gear = SpurGear(int(input("Number of teeth: \n ")), float(input("Outside Diameter (same as Addendum Circle): \n ")))
gear.module()
gear.pitch_circle_diameter()
gear.circular_pitch()
gear.diametral_pitch()
gear.addendum()
gear.addendum_circle_diameter()
gear.clearance()
gear.deddendum()
gear.deddendum_circle_diameter()
gear.pressure_angle()
gear.circular_pitch_angle()
gear.face_width()
gear.backlash()